operations:
  - get-finances-sales-daily-units
  - get-finances-sales-period-units
  - get-delivery-statistics
  - get-orders-client-statistics
  - get-staff-productivity
  - get-delivery-vouchers
  - get-production-stop-sales-saleschannels
  - get-production-stop-sales-statistics-ingredients
  - get-production-unit-workload-by-orders
  - get-production-unit-workload-by-products
  - get-production-orders-handover-time-statistics
  - get-staff-meals
  - get-all-units
