sales: [выручка, продажи, оборот, sales, revenue]
orders_count: [заказы, количество заказов, число заказов, orders, orders count]
average_check: [средний чек, ср чек, average check, average order value, aov]
sales_by_channel: [продажи по каналам, продажи доставки, delivery sales]
delivery_sales: [выручка доставки, выручка с доставки, выручка по доставке, продажи доставки]
delivery_orders_count: [заказы доставки]
average_delivery_time_seconds: [среднее время доставки, время доставки]
average_cooking_time_seconds: [среднее время приготовления]
average_heated_shelf_time_seconds: [время на тепловой полке]
average_trip_time_seconds: [среднее время поездки]
late_orders_count: [опоздавшие заказы]
courier_app_usage_percent: [использование приложения курьера]
orders_per_courier_hour: [заказов на курьерский час]
courier_utilization_percent: [утилизация курьеров]
new_clients_count: [новые клиенты]
dine_in_new_clients_count: [новые клиенты в ресторане]
delivery_takeaway_new_clients_count: [новые клиенты доставки и самовывоза]
old_clients_count: [старые клиенты]
labor_hours: [трудочасы, часы труда]
productivity_sales: [продажи производительности]
sales_per_labor_hour: [продажи на трудочас]
products_per_labor_hour: [продуктов на трудочас]
productivity_average_heated_shelf_time: [среднее время на тепловой полке персонал]
vouchers_count: [сертификаты за опоздание, ваучеры]
ingredient_stops_count: [стопы ингредиентов, количество стопов ингредиентов]
ingredient_stop_duration_hours: [длительность стопов ингредиентов, часы стопов ингредиентов]
channel_stops_count: [стопы каналов продаж]
channel_stop_duration_hours: [длительность стопов каналов]
workload_orders_count: [нагрузка по заказам]
workload_products_count: [нагрузка по продуктам]
average_order_handover_time_seconds: [время выдачи заказа, среднее время выдачи заказа, время до выдачи заказа, order handover time]
staff_meals_cost: [деньги на питание команды, потрачено на питание команды, сумма питания команды, стоимость питания команды, расходы на питание команды, staff meals cost]
